namespace SolvedAC;

/**
 * 단체 유형입니다.
 */
enum OrganizationType {
  /**
   * 대학교
   */
  University: "university",

  /**
   * 회사
   */
  Company: "company",

  /**
   * 커뮤니티
   */
  Community: "community",

  /**
   * 고등학교
   */
  HighSchool: "high_school",

  /**
   * 중학교
   */
  MiddleSchool: "middle_school",

  /**
   * 초등학교
   */
  ElementarySchool: "elementary_school",

  /**
   * 기타
   */
  Others: "undefined",
}
